session_name: react starter
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: dev
  layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  start_directory: ./
  panes:
  - focus: true
  - pane
  - pane
  - '[ -d node_modules ] && npm install && reset'
